[package]
name = "dodrio-js-frameworks-benchmark"
version = "0.1.0"
authors = ["Till Schneidereit <till@tillschneidereit.net>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[features]

[dependencies]
console_error_panic_hook = "0.1.6"
console_log = "0.1.2"
dodrio = { git = "https://github.com/fitzgen/dodrio/" }
log = "0.4.6"
js-sys = "0.3.5"
wasm-bindgen = "0.2.37"

[dependencies.web-sys]
version = "0.3.14"
features = [
  "console",
  "Document",
  "Event",
  "EventTarget",
  "HtmlElement",
  "MouseEvent",
  "Node",
  "Window",
]

[dev-dependencies]
wasm-bindgen-test = "0.2.37"
